---
version: '3.4'
services:
  test:
    build:
      context: "."
      dockerfile: Dockerfile.ci
    volumes:
    - "./vendor/bundle:/usr/local/bundle"
    environment:
      RACK_ENV: test
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
    links:
    - mysql
  mysql:
    image: mysql:5.6.23
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
